"./log/*.log" "./log/player_vars_journal" {
	daily
	minsize 131072
	missingok
	notifempty
	rotate 9999

	copytruncate

	compress
	compresscmd /usr/bin/xz
	uncompresscmd /usr/bin/unxz
	compressext .xz
	compressoptions -9 -e
}
